package demo.sapi.models;

// Generated 20 nov. 2014 18:11:23 by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.codehaus.jackson.annotate.JsonBackReference;
import org.hibernate.annotations.ColumnTransformer;

import fr.socgen.sis.aga.tools.AgaConstants;

/**
 * Expenses generated by hbm2java
 */
@Entity
@Table(name = "EXPENSES", catalog = "`sis-aga`")
public class Expenses implements java.io.Serializable {

    private Integer expenseId;
    @JsonBackReference
    private Rubrique rubrique;
    private String nom;
    private String prenom;
    private String matricule;
    private String caEmploye;
    private String ndfSaisiePar;
    private String numNdf;
    private String descNdf;
    private String comment;
    private String statut;
    private int numLigne;
    private String caPayeur;
    private String guichet;
    private String depensePerso;
    private String rubrique_1;
    private String compte;
    private String horsPolitique;
    private String prestaReference;
    private int nbrDeNuites;
    private String rejet;
    private String localisation;
    private Date dateTransaction;
    private Date datePaiement;
    private String modeDePaiement;
    private BigDecimal montantTtc;
    private BigDecimal montantHt;
    private BigDecimal montantTva;
    private BigDecimal montantHtr;
    private Date dateDeSoumission;
    private Date dateImputationComptable;
    private String libelleEmploi;
    private String statutAgent;
    private String motif;

    public Expenses() {
    }

    public Expenses(Rubrique rubrique, String nom, String prenom,
            String matricule, String caEmploye, String ndfSaisiePar,
            String numNdf, String descNdf, String statut, int numLigne,
            String caPayeur, String guichet, String depensePerso,
            String rubrique_1, String compte, String horsPolitique,
            String prestaReference, int nbrDeNuites, String rejet,
            String localisation, Date dateTransaction, Date datePaiement,
            String modeDePaiement, BigDecimal montantTtc, BigDecimal montantHt,
            BigDecimal montantTva, BigDecimal montantHtr,
            Date dateDeSoumission, Date dateImputationComptable,
            String libelleEmploi, String statutAgent, String motif) {
        this.rubrique = rubrique;
        this.nom = nom;
        this.prenom = prenom;
        this.matricule = matricule;
        this.caEmploye = caEmploye;
        this.ndfSaisiePar = ndfSaisiePar;
        this.numNdf = numNdf;
        this.descNdf = descNdf;
        this.statut = statut;
        this.numLigne = numLigne;
        this.caPayeur = caPayeur;
        this.guichet = guichet;
        this.depensePerso = depensePerso;
        this.rubrique_1 = rubrique_1;
        this.compte = compte;
        this.horsPolitique = horsPolitique;
        this.prestaReference = prestaReference;
        this.nbrDeNuites = nbrDeNuites;
        this.rejet = rejet;
        this.localisation = localisation;
        this.dateTransaction = dateTransaction;
        this.datePaiement = datePaiement;
        this.modeDePaiement = modeDePaiement;
        this.montantTtc = montantTtc;
        this.montantHt = montantHt;
        this.montantTva = montantTva;
        this.montantHtr = montantHtr;
        this.dateDeSoumission = dateDeSoumission;
        this.dateImputationComptable = dateImputationComptable;
        this.libelleEmploi = libelleEmploi;
        this.statutAgent = statutAgent;
        this.motif = motif;
    }

    public Expenses(Rubrique rubrique, String nom, String prenom,
            String matricule, String caEmploye, String ndfSaisiePar,
            String numNdf, String descNdf, String comment, String statut,
            int numLigne, String caPayeur, String guichet, String depensePerso,
            String rubrique_1, String compte, String horsPolitique,
            String prestaReference, int nbrDeNuites, String rejet,
            String localisation, Date dateTransaction, Date datePaiement,
            String modeDePaiement, BigDecimal montantTtc, BigDecimal montantHt,
            BigDecimal montantTva, BigDecimal montantHtr,
            Date dateDeSoumission, Date dateImputationComptable,
            String libelleEmploi, String statutAgent, String motif) {
        this.rubrique = rubrique;
        this.nom = nom;
        this.prenom = prenom;
        this.matricule = matricule;
        this.caEmploye = caEmploye;
        this.ndfSaisiePar = ndfSaisiePar;
        this.numNdf = numNdf;
        this.descNdf = descNdf;
        this.comment = comment;
        this.statut = statut;
        this.numLigne = numLigne;
        this.caPayeur = caPayeur;
        this.guichet = guichet;
        this.depensePerso = depensePerso;
        this.rubrique_1 = rubrique_1;
        this.compte = compte;
        this.horsPolitique = horsPolitique;
        this.prestaReference = prestaReference;
        this.nbrDeNuites = nbrDeNuites;
        this.rejet = rejet;
        this.localisation = localisation;
        this.dateTransaction = dateTransaction;
        this.datePaiement = datePaiement;
        this.modeDePaiement = modeDePaiement;
        this.montantTtc = montantTtc;
        this.montantHt = montantHt;
        this.montantTva = montantTva;
        this.montantHtr = montantHtr;
        this.dateDeSoumission = dateDeSoumission;
        this.dateImputationComptable = dateImputationComptable;
        this.libelleEmploi = libelleEmploi;
        this.statutAgent = statutAgent;
        this.motif = motif;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "EXPENSE_ID", unique = true, nullable = false)
    public Integer getExpenseId() {
        return this.expenseId;
    }

    public void setExpenseId(Integer expenseId) {
        this.expenseId = expenseId;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "RUBRIQUE_ID", nullable = false)
    public Rubrique getRubrique() {
        return this.rubrique;
    }

    public void setRubrique(Rubrique rubrique) {
        this.rubrique = rubrique;
    }

    @Column(name = "NOM", nullable = false, columnDefinition = "blob")
    @ColumnTransformer(read = "CONVERT(AES_DECRYPT(NOM, '"
            + SapiConstants.AES_KEY + "') USING utf8)", write = "AES_ENCRYPT(CONVERT(? USING utf8), '"
            + SapiConstants.AES_KEY + "')")
    public String getNom() {
        return this.nom;
    }

    public void setNom(String nom) {
        this.nom = nom;
    }

    @Column(name = "PRENOM", nullable = false, columnDefinition = "blob")
    @ColumnTransformer(read = "CONVERT(AES_DECRYPT(PRENOM, '"
            + SapiConstants.AES_KEY + "') USING utf8)", write = "AES_ENCRYPT(CONVERT(? USING utf8), '"
            + SapiConstants.AES_KEY + "')")
    public String getPrenom() {
        return this.prenom;
    }

    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }

    @Column(name = "MATRICULE", nullable = false, columnDefinition = "blob")
    @ColumnTransformer(read = "CONVERT(AES_DECRYPT(MATRICULE, '"
            + SapiConstants.AES_KEY + "') USING utf8)", write = "AES_ENCRYPT(CONVERT(? USING utf8), '"
            + SapiConstants.AES_KEY + "')")
    public String getMatricule() {
        return this.matricule;
    }

    public void setMatricule(String matricule) {
        this.matricule = matricule;
    }

    @Column(name = "CA_EMPLOYE", nullable = false, length = 10)
    public String getCaEmploye() {
        return this.caEmploye;
    }

    public void setCaEmploye(String caEmploye) {
        this.caEmploye = caEmploye;
    }

    @Column(name = "NDF_SAISIE_PAR", nullable = false, columnDefinition = "blob")
    @ColumnTransformer(read = "CONVERT(AES_DECRYPT(NDF_SAISIE_PAR, '"
            + SapiConstants.AES_KEY + "') USING utf8)", write = "AES_ENCRYPT(CONVERT(? USING utf8), '"
            + SapiConstants.AES_KEY + "')")
    public String getNdfSaisiePar() {
        return this.ndfSaisiePar;
    }

    public void setNdfSaisiePar(String ndfSaisiePar) {
        this.ndfSaisiePar = ndfSaisiePar;
    }

    @Column(name = "NUM_NDF", nullable = false, length = 10)
    public String getNumNdf() {
        return this.numNdf;
    }

    public void setNumNdf(String numNdf) {
        this.numNdf = numNdf;
    }

    @Column(name = "DESC_NDF", nullable = false)
    public String getDescNdf() {
        return this.descNdf;
    }

    public void setDescNdf(String descNdf) {
        this.descNdf = descNdf;
    }

    @Column(name = "COMMENT")
    public String getComment() {
        return this.comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    @Column(name = "STATUT", nullable = false, length = 45)
    public String getStatut() {
        return this.statut;
    }

    public void setStatut(String statut) {
        this.statut = statut;
    }

    @Column(name = "NUM_LIGNE", nullable = false)
    public int getNumLigne() {
        return this.numLigne;
    }

    public void setNumLigne(int numLigne) {
        this.numLigne = numLigne;
    }

    @Column(name = "CA_PAYEUR", nullable = false, length = 10)
    public String getCaPayeur() {
        return this.caPayeur;
    }

    public void setCaPayeur(String caPayeur) {
        this.caPayeur = caPayeur;
    }

    @Column(name = "GUICHET", nullable = false, length = 10)
    public String getGuichet() {
        return this.guichet;
    }

    public void setGuichet(String guichet) {
        this.guichet = guichet;
    }

    @Column(name = "DEPENSE_PERSO", nullable = false, length = 1)
    public String getDepensePerso() {
        return this.depensePerso;
    }

    public void setDepensePerso(String depensePerso) {
        this.depensePerso = depensePerso;
    }

    @Column(name = "RUBRIQUE", nullable = false, length = 45)
    public String getRubrique_1() {
        return this.rubrique_1;
    }

    public void setRubrique_1(String rubrique_1) {
        this.rubrique_1 = rubrique_1;
    }

    @Column(name = "COMPTE", nullable = false, length = 14)
    public String getCompte() {
        return this.compte;
    }

    public void setCompte(String compte) {
        this.compte = compte;
    }

    @Column(name = "HORS_POLITIQUE", nullable = false, length = 1)
    public String getHorsPolitique() {
        return this.horsPolitique;
    }

    public void setHorsPolitique(String horsPolitique) {
        this.horsPolitique = horsPolitique;
    }

    @Column(name = "PRESTA_REFERENCE", nullable = false, length = 1)
    public String getPrestaReference() {
        return this.prestaReference;
    }

    public void setPrestaReference(String prestaReference) {
        this.prestaReference = prestaReference;
    }

    @Column(name = "NBR_DE_NUITES", nullable = false)
    public int getNbrDeNuites() {
        return this.nbrDeNuites;
    }

    public void setNbrDeNuites(int nbrDeNuites) {
        this.nbrDeNuites = nbrDeNuites;
    }

    @Column(name = "REJET", nullable = false, length = 45)
    public String getRejet() {
        return this.rejet;
    }

    public void setRejet(String rejet) {
        this.rejet = rejet;
    }

    @Column(name = "LOCALISATION", nullable = false, length = 45)
    public String getLocalisation() {
        return this.localisation;
    }

    public void setLocalisation(String localisation) {
        this.localisation = localisation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_TRANSACTION", nullable = false, length = 0)
    public Date getDateTransaction() {
        return this.dateTransaction;
    }

    public void setDateTransaction(Date dateTransaction) {
        this.dateTransaction = dateTransaction;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_PAIEMENT", nullable = false, length = 0)
    public Date getDatePaiement() {
        return this.datePaiement;
    }

    public void setDatePaiement(Date datePaiement) {
        this.datePaiement = datePaiement;
    }

    @Column(name = "MODE_DE_PAIEMENT", nullable = false, length = 45)
    public String getModeDePaiement() {
        return this.modeDePaiement;
    }

    public void setModeDePaiement(String modeDePaiement) {
        this.modeDePaiement = modeDePaiement;
    }

    @Column(name = "MONTANT_TTC", nullable = false, precision = 10)
    public BigDecimal getMontantTtc() {
        return this.montantTtc;
    }

    public void setMontantTtc(BigDecimal montantTtc) {
        this.montantTtc = montantTtc;
    }

    @Column(name = "MONTANT_HT", nullable = false, precision = 10)
    public BigDecimal getMontantHt() {
        return this.montantHt;
    }

    public void setMontantHt(BigDecimal montantHt) {
        this.montantHt = montantHt;
    }

    @Column(name = "MONTANT_TVA", nullable = false, precision = 10)
    public BigDecimal getMontantTva() {
        return this.montantTva;
    }

    public void setMontantTva(BigDecimal montantTva) {
        this.montantTva = montantTva;
    }

    @Column(name = "MONTANT_HTR", nullable = false, precision = 10)
    public BigDecimal getMontantHtr() {
        return this.montantHtr;
    }

    public void setMontantHtr(BigDecimal montantHtr) {
        this.montantHtr = montantHtr;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_DE_SOUMISSION", nullable = false, length = 0)
    public Date getDateDeSoumission() {
        return this.dateDeSoumission;
    }

    public void setDateDeSoumission(Date dateDeSoumission) {
        this.dateDeSoumission = dateDeSoumission;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_IMPUTATION_COMPTABLE", nullable = false, length = 0)
    public Date getDateImputationComptable() {
        return this.dateImputationComptable;
    }

    public void setDateImputationComptable(Date dateImputationComptable) {
        this.dateImputationComptable = dateImputationComptable;
    }

    @Column(name = "LIBELLE_EMPLOI", nullable = false, length = 45)
    public String getLibelleEmploi() {
        return this.libelleEmploi;
    }

    public void setLibelleEmploi(String libelleEmploi) {
        this.libelleEmploi = libelleEmploi;
    }

    @Column(name = "STATUT_AGENT", nullable = false, length = 10)
    public String getStatutAgent() {
        return this.statutAgent;
    }

    public void setStatutAgent(String statutAgent) {
        this.statutAgent = statutAgent;
    }

    @Column(name = "MOTIF", nullable = false, length = 10)
    public String getMotif() {
        return this.motif;
    }

    public void setMotif(String motif) {
        this.motif = motif;
    }

}
