package demo.sapi.models;

// Generated 20 nov. 2014 18:11:23 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Perimeter generated by hbm2java
 */
@Entity
@Table(name = "PERIMETER", catalog = "`sis-aga`")
public class Perimeter implements java.io.Serializable {

    private Integer id;
    private Users users;
    private String nid5;
    private String nid4;
    private String nid3;

    public Perimeter() {
    }

    public Perimeter(Users users, String nid5, String nid4, String nid3) {
        this.users = users;
        this.nid5 = nid5;
        this.nid4 = nid4;
        this.nid3 = nid3;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "UID")
    public Users getUsers() {
        return this.users;
    }

    public void setUsers(Users users) {
        this.users = users;
    }

    @Column(name = "NID5", length = 10)
    public String getNid5() {
        return this.nid5;
    }

    public void setNid5(String nid5) {
        this.nid5 = nid5;
    }

    @Column(name = "NID4", length = 10)
    public String getNid4() {
        return this.nid4;
    }

    public void setNid4(String nid4) {
        this.nid4 = nid4;
    }

    @Column(name = "NID3", length = 10)
    public String getNid3() {
        return this.nid3;
    }

    public void setNid3(String nid3) {
        this.nid3 = nid3;
    }

}
