package demo.sapi.models;

// Generated 20 nov. 2014 18:11:23 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Profil generated by hbm2java
 */
@Entity
@Table(name = "PROFIL", catalog = "`sis-aga`")
public class Profil implements java.io.Serializable {

    private Integer id;
    private String libProfil;
    private String role;
    private Set<Users> userses = new HashSet(0);

    public Profil() {
    }

    public Profil(String libProfil, String role) {
        this.libProfil = libProfil;
        this.role = role;
    }

    public Profil(String libProfil, String role, Set<Users> userses) {
        this.libProfil = libProfil;
        this.role = role;
        this.userses = userses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "LIB_PROFIL", nullable = false, length = 30)
    public String getLibProfil() {
        return this.libProfil;
    }

    public void setLibProfil(String libProfil) {
        this.libProfil = libProfil;
    }

    @Column(name = "ROLE", nullable = false, length = 20)
    public String getRole() {
        return this.role;
    }

    public void setRole(String role) {
        this.role = role;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "profil")
    public Set<Users> getUserses() {
        return this.userses;
    }

    public void setUserses(Set<Users> userses) {
        this.userses = userses;
    }

}
