package demo.sapi.models;

// Generated 20 nov. 2014 18:11:23 by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.codehaus.jackson.annotate.JsonIgnore;
import org.codehaus.jackson.annotate.JsonManagedReference;

/**
 * Rubrique generated by hbm2java
 */
@Entity
@Table(name = "RUBRIQUE", catalog = "`sis-aga`")
public class Rubrique implements java.io.Serializable {

    private Integer rubriqueId;
    private String rubrique;
    private String descr;
    @JsonManagedReference
    @JsonIgnore
    private Set<Expenses> expenseses = new HashSet(0);

    public Rubrique() {
    }

    public Rubrique(String rubrique, String descr) {
        this.rubrique = rubrique;
        this.descr = descr;
    }

    public Rubrique(String rubrique, String descr, Set<Expenses> expenseses) {
        this.rubrique = rubrique;
        this.descr = descr;
        this.expenseses = expenseses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "RUBRIQUE_ID", unique = true, nullable = false)
    public Integer getRubriqueId() {
        return this.rubriqueId;
    }

    public void setRubriqueId(Integer rubriqueId) {
        this.rubriqueId = rubriqueId;
    }

    @Column(name = "RUBRIQUE", nullable = false, length = 100)
    public String getRubrique() {
        return this.rubrique;
    }

    public void setRubrique(String rubrique) {
        this.rubrique = rubrique;
    }

    @Column(name = "DESCR", nullable = false, length = 150)
    public String getDescr() {
        return this.descr;
    }

    public void setDescr(String descr) {
        this.descr = descr;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "rubrique")
    public Set<Expenses> getExpenseses() {
        return this.expenseses;
    }

    public void setExpenseses(Set<Expenses> expenseses) {
        this.expenseses = expenseses;
    }

}
