package demo.sapi.models;

// Generated 9 d�c. 2014 19:06:28 by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.IDENTITY;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.ColumnTransformer;

import fr.socgen.sis.aga.tools.AgaConstants;

/**
 * TelMobile generated by hbm2java
 */
@Entity
@Table(name = "TEL_MOBILE", catalog = "`sis-aga`")
public class TelMobile implements java.io.Serializable {

    private Integer idtelMobile;
    private String utilisateur;
    private String etatLignetel;
    private String formuleAbo;
    private String centreFac;
    private String operateur;
    private String modeleMobile;
    private String numSerieMobile;
    private String typologieMobile;
    private String imeiMobile;
    private String terminalMobile;
    private String numappel;
    private BigDecimal totalFac;
    private BigDecimal totalAbo;
    private BigDecimal totalConso;
    private BigDecimal totalServicesrem;
    private BigDecimal totalNational;
    private BigDecimal totalNumspeciaux;
    private BigDecimal totalInternational;
    private BigDecimal totalRoamingSortant;
    private BigDecimal totalRoamingEntrant;
    private BigDecimal totalSms;
    private BigDecimal totalData;
    private long dureeNational;
    private long dureeInternational;
    private long dureeRoamingSortant;
    private long dureeRoamingEntrant;
    private String debitNational;
    private long debitInternational;
    private long nbSms;
    private Date dateFac;
    private String idniveau0;
    private BigDecimal smsNational;
    private BigDecimal smsInternational;
    private int nbSmsNational;
    private int nbSmsInternational;
    private String typoEffco;
    private String typologie;

    public TelMobile() {
    }

    public TelMobile(String etatLignetel, String formuleAbo, String centreFac,
            String operateur, String modeleMobile, String numSerieMobile,
            String typologieMobile, String imeiMobile, String terminalMobile,
            BigDecimal totalFac, BigDecimal totalAbo, BigDecimal totalConso,
            BigDecimal totalServicesrem, BigDecimal totalNational,
            BigDecimal totalNumspeciaux, BigDecimal totalInternational,
            BigDecimal totalRoamingSortant, BigDecimal totalRoamingEntrant,
            BigDecimal totalSms, BigDecimal totalData, long dureeNational,
            long dureeInternational, long dureeRoamingSortant,
            long dureeRoamingEntrant, String debitNational,
            long debitInternational, long nbSms, Date dateFac,
            BigDecimal smsNational, BigDecimal smsInternational,
            int nbSmsNational, int nbSmsInternational, String typoEffco,
            String typologie) {
        this.etatLignetel = etatLignetel;
        this.formuleAbo = formuleAbo;
        this.centreFac = centreFac;
        this.operateur = operateur;
        this.modeleMobile = modeleMobile;
        this.numSerieMobile = numSerieMobile;
        this.typologieMobile = typologieMobile;
        this.imeiMobile = imeiMobile;
        this.terminalMobile = terminalMobile;
        this.totalFac = totalFac;
        this.totalAbo = totalAbo;
        this.totalConso = totalConso;
        this.totalServicesrem = totalServicesrem;
        this.totalNational = totalNational;
        this.totalNumspeciaux = totalNumspeciaux;
        this.totalInternational = totalInternational;
        this.totalRoamingSortant = totalRoamingSortant;
        this.totalRoamingEntrant = totalRoamingEntrant;
        this.totalSms = totalSms;
        this.totalData = totalData;
        this.dureeNational = dureeNational;
        this.dureeInternational = dureeInternational;
        this.dureeRoamingSortant = dureeRoamingSortant;
        this.dureeRoamingEntrant = dureeRoamingEntrant;
        this.debitNational = debitNational;
        this.debitInternational = debitInternational;
        this.nbSms = nbSms;
        this.dateFac = dateFac;
        this.smsNational = smsNational;
        this.smsInternational = smsInternational;
        this.nbSmsNational = nbSmsNational;
        this.nbSmsInternational = nbSmsInternational;
        this.typoEffco = typoEffco;
        this.typologie = typologie;
    }

    public TelMobile(String utilisateur, String etatLignetel,
            String formuleAbo, String centreFac, String operateur,
            String modeleMobile, String numSerieMobile, String typologieMobile,
            String imeiMobile, String terminalMobile, String numappel,
            BigDecimal totalFac, BigDecimal totalAbo, BigDecimal totalConso,
            BigDecimal totalServicesrem, BigDecimal totalNational,
            BigDecimal totalNumspeciaux, BigDecimal totalInternational,
            BigDecimal totalRoamingSortant, BigDecimal totalRoamingEntrant,
            BigDecimal totalSms, BigDecimal totalData, long dureeNational,
            long dureeInternational, long dureeRoamingSortant,
            long dureeRoamingEntrant, String debitNational,
            long debitInternational, long nbSms, Date dateFac,
            String idniveau0, BigDecimal smsNational,
            BigDecimal smsInternational, int nbSmsNational,
            int nbSmsInternational, String typoEffco, String typologie) {
        this.utilisateur = utilisateur;
        this.etatLignetel = etatLignetel;
        this.formuleAbo = formuleAbo;
        this.centreFac = centreFac;
        this.operateur = operateur;
        this.modeleMobile = modeleMobile;
        this.numSerieMobile = numSerieMobile;
        this.typologieMobile = typologieMobile;
        this.imeiMobile = imeiMobile;
        this.terminalMobile = terminalMobile;
        this.numappel = numappel;
        this.totalFac = totalFac;
        this.totalAbo = totalAbo;
        this.totalConso = totalConso;
        this.totalServicesrem = totalServicesrem;
        this.totalNational = totalNational;
        this.totalNumspeciaux = totalNumspeciaux;
        this.totalInternational = totalInternational;
        this.totalRoamingSortant = totalRoamingSortant;
        this.totalRoamingEntrant = totalRoamingEntrant;
        this.totalSms = totalSms;
        this.totalData = totalData;
        this.dureeNational = dureeNational;
        this.dureeInternational = dureeInternational;
        this.dureeRoamingSortant = dureeRoamingSortant;
        this.dureeRoamingEntrant = dureeRoamingEntrant;
        this.debitNational = debitNational;
        this.debitInternational = debitInternational;
        this.nbSms = nbSms;
        this.dateFac = dateFac;
        this.idniveau0 = idniveau0;
        this.smsNational = smsNational;
        this.smsInternational = smsInternational;
        this.nbSmsNational = nbSmsNational;
        this.nbSmsInternational = nbSmsInternational;
        this.typoEffco = typoEffco;
        this.typologie = typologie;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "IDTEL_MOBILE", unique = true, nullable = false)
    public Integer getIdtelMobile() {
        return this.idtelMobile;
    }

    public void setIdtelMobile(Integer idtelMobile) {
        this.idtelMobile = idtelMobile;
    }

    @Column(name = "UTILISATEUR", columnDefinition = "blob")
    @ColumnTransformer(read = "CONVERT(AES_DECRYPT(UTILISATEUR, '"
            + SapiConstants.AES_KEY + "') USING utf8)", write = "AES_ENCRYPT(CONVERT(? USING utf8), '"
            + SapiConstants.AES_KEY + "')")
    public String getUtilisateur() {
        return this.utilisateur;
    }

    public void setUtilisateur(String utilisateur) {
        this.utilisateur = utilisateur;
    }

    @Column(name = "ETAT_LIGNETEL", nullable = false, length = 15)
    public String getEtatLignetel() {
        return this.etatLignetel;
    }

    public void setEtatLignetel(String etatLignetel) {
        this.etatLignetel = etatLignetel;
    }

    @Column(name = "FORMULE_ABO", nullable = false, length = 50)
    public String getFormuleAbo() {
        return this.formuleAbo;
    }

    public void setFormuleAbo(String formuleAbo) {
        this.formuleAbo = formuleAbo;
    }

    @Column(name = "CENTRE_FAC", nullable = false, length = 15)
    public String getCentreFac() {
        return this.centreFac;
    }

    public void setCentreFac(String centreFac) {
        this.centreFac = centreFac;
    }

    @Column(name = "OPERATEUR", nullable = false, length = 50)
    public String getOperateur() {
        return this.operateur;
    }

    public void setOperateur(String operateur) {
        this.operateur = operateur;
    }

    @Column(name = "MODELE_MOBILE", nullable = false, length = 50)
    public String getModeleMobile() {
        return this.modeleMobile;
    }

    public void setModeleMobile(String modeleMobile) {
        this.modeleMobile = modeleMobile;
    }

    @Column(name = "NUM_SERIE_MOBILE", nullable = false, length = 50)
    public String getNumSerieMobile() {
        return this.numSerieMobile;
    }

    public void setNumSerieMobile(String numSerieMobile) {
        this.numSerieMobile = numSerieMobile;
    }

    @Column(name = "TYPOLOGIE_MOBILE", nullable = false, length = 20)
    public String getTypologieMobile() {
        return this.typologieMobile;
    }

    public void setTypologieMobile(String typologieMobile) {
        this.typologieMobile = typologieMobile;
    }

    @Column(name = "IMEI_MOBILE", nullable = false, length = 20)
    public String getImeiMobile() {
        return this.imeiMobile;
    }

    public void setImeiMobile(String imeiMobile) {
        this.imeiMobile = imeiMobile;
    }

    @Column(name = "TERMINAL_MOBILE", nullable = false, length = 30)
    public String getTerminalMobile() {
        return this.terminalMobile;
    }

    public void setTerminalMobile(String terminalMobile) {
        this.terminalMobile = terminalMobile;
    }

    @Column(name = "NUMAPPEL", columnDefinition = "blob")
    @ColumnTransformer(read = "CONVERT(AES_DECRYPT(NUMAPPEL, '"
            + SapiConstants.AES_KEY + "') USING utf8)", write = "AES_ENCRYPT(CONVERT(? USING utf8), '"
            + SapiConstants.AES_KEY + "')")
    public String getNumappel() {
        return this.numappel;
    }

    public void setNumappel(String numappel) {
        this.numappel = numappel;
    }

    @Column(name = "TOTAL_FAC", nullable = false, precision = 24, scale = 6)
    public BigDecimal getTotalFac() {
        return this.totalFac;
    }

    public void setTotalFac(BigDecimal totalFac) {
        this.totalFac = totalFac;
    }

    @Column(name = "TOTAL_ABO", nullable = false, precision = 24, scale = 6)
    public BigDecimal getTotalAbo() {
        return this.totalAbo;
    }

    public void setTotalAbo(BigDecimal totalAbo) {
        this.totalAbo = totalAbo;
    }

    @Column(name = "TOTAL_CONSO", nullable = false, precision = 24, scale = 6)
    public BigDecimal getTotalConso() {
        return this.totalConso;
    }

    public void setTotalConso(BigDecimal totalConso) {
        this.totalConso = totalConso;
    }

    @Column(name = "TOTAL_SERVICESREM", nullable = false, precision = 24, scale = 6)
    public BigDecimal getTotalServicesrem() {
        return this.totalServicesrem;
    }

    public void setTotalServicesrem(BigDecimal totalServicesrem) {
        this.totalServicesrem = totalServicesrem;
    }

    @Column(name = "TOTAL_NATIONAL", nullable = false, precision = 24, scale = 6)
    public BigDecimal getTotalNational() {
        return this.totalNational;
    }

    public void setTotalNational(BigDecimal totalNational) {
        this.totalNational = totalNational;
    }

    @Column(name = "TOTAL_NUMSPECIAUX", nullable = false, precision = 24, scale = 6)
    public BigDecimal getTotalNumspeciaux() {
        return this.totalNumspeciaux;
    }

    public void setTotalNumspeciaux(BigDecimal totalNumspeciaux) {
        this.totalNumspeciaux = totalNumspeciaux;
    }

    @Column(name = "TOTAL_INTERNATIONAL", nullable = false, precision = 24, scale = 6)
    public BigDecimal getTotalInternational() {
        return this.totalInternational;
    }

    public void setTotalInternational(BigDecimal totalInternational) {
        this.totalInternational = totalInternational;
    }

    @Column(name = "TOTAL_ROAMING_SORTANT", nullable = false, precision = 24, scale = 6)
    public BigDecimal getTotalRoamingSortant() {
        return this.totalRoamingSortant;
    }

    public void setTotalRoamingSortant(BigDecimal totalRoamingSortant) {
        this.totalRoamingSortant = totalRoamingSortant;
    }

    @Column(name = "TOTAL_ROAMING_ENTRANT", nullable = false, precision = 24, scale = 6)
    public BigDecimal getTotalRoamingEntrant() {
        return this.totalRoamingEntrant;
    }

    public void setTotalRoamingEntrant(BigDecimal totalRoamingEntrant) {
        this.totalRoamingEntrant = totalRoamingEntrant;
    }

    @Column(name = "TOTAL_SMS", nullable = false, precision = 24, scale = 6)
    public BigDecimal getTotalSms() {
        return this.totalSms;
    }

    public void setTotalSms(BigDecimal totalSms) {
        this.totalSms = totalSms;
    }

    @Column(name = "TOTAL_DATA", nullable = false, precision = 24, scale = 6)
    public BigDecimal getTotalData() {
        return this.totalData;
    }

    public void setTotalData(BigDecimal totalData) {
        this.totalData = totalData;
    }

    @Column(name = "DUREE_NATIONAL", nullable = false)
    public long getDureeNational() {
        return this.dureeNational;
    }

    public void setDureeNational(long dureeNational) {
        this.dureeNational = dureeNational;
    }

    @Column(name = "DUREE_INTERNATIONAL", nullable = false)
    public long getDureeInternational() {
        return this.dureeInternational;
    }

    public void setDureeInternational(long dureeInternational) {
        this.dureeInternational = dureeInternational;
    }

    @Column(name = "DUREE_ROAMING_SORTANT", nullable = false)
    public long getDureeRoamingSortant() {
        return this.dureeRoamingSortant;
    }

    public void setDureeRoamingSortant(long dureeRoamingSortant) {
        this.dureeRoamingSortant = dureeRoamingSortant;
    }

    @Column(name = "DUREE_ROAMING_ENTRANT", nullable = false)
    public long getDureeRoamingEntrant() {
        return this.dureeRoamingEntrant;
    }

    public void setDureeRoamingEntrant(long dureeRoamingEntrant) {
        this.dureeRoamingEntrant = dureeRoamingEntrant;
    }

    @Column(name = "DEBIT_NATIONAL", nullable = false, length = 50)
    public String getDebitNational() {
        return this.debitNational;
    }

    public void setDebitNational(String debitNational) {
        this.debitNational = debitNational;
    }

    @Column(name = "DEBIT_INTERNATIONAL", nullable = false, precision = 10, scale = 0, columnDefinition = "decimal")
    public long getDebitInternational() {
        return this.debitInternational;
    }

    public void setDebitInternational(long debitInternational) {
        this.debitInternational = debitInternational;
    }

    @Column(name = "NB_SMS", nullable = false, precision = 10, scale = 0, columnDefinition = "decimal")
    public long getNbSms() {
        return this.nbSms;
    }

    public void setNbSms(long nbSms) {
        this.nbSms = nbSms;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATE_FAC", nullable = false, length = 0)
    public Date getDateFac() {
        return this.dateFac;
    }

    public void setDateFac(Date dateFac) {
        this.dateFac = dateFac;
    }

    @Column(name = "IDNIVEAU0", length = 10)
    public String getIdniveau0() {
        return this.idniveau0;
    }

    public void setIdniveau0(String idniveau0) {
        this.idniveau0 = idniveau0;
    }

    @Column(name = "SMS_NATIONAL", nullable = false, precision = 10)
    public BigDecimal getSmsNational() {
        return this.smsNational;
    }

    public void setSmsNational(BigDecimal smsNational) {
        this.smsNational = smsNational;
    }

    @Column(name = "SMS_INTERNATIONAL", nullable = false, precision = 10)
    public BigDecimal getSmsInternational() {
        return this.smsInternational;
    }

    public void setSmsInternational(BigDecimal smsInternational) {
        this.smsInternational = smsInternational;
    }

    @Column(name = "NB_SMS_NATIONAL", nullable = false)
    public int getNbSmsNational() {
        return this.nbSmsNational;
    }

    public void setNbSmsNational(int nbSmsNational) {
        this.nbSmsNational = nbSmsNational;
    }

    @Column(name = "NB_SMS_INTERNATIONAL", nullable = false)
    public int getNbSmsInternational() {
        return this.nbSmsInternational;
    }

    public void setNbSmsInternational(int nbSmsInternational) {
        this.nbSmsInternational = nbSmsInternational;
    }

    @Column(name = "TYPO_EFFCO", nullable = false)
    public String getTypoEffco() {
        return this.typoEffco;
    }

    public void setTypoEffco(String typoEffco) {
        this.typoEffco = typoEffco;
    }

    @Column(name = "TYPOLOGIE", nullable = false)
    public String getTypologie() {
        return this.typologie;
    }

    public void setTypologie(String typologie) {
        this.typologie = typologie;
    }

}
