package demo.sapi.models;

// Generated 20 nov. 2014 18:11:23 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Uploadmobile generated by hbm2java
 */
@Entity
@Table(name = "UPLOADMOBILE", catalog = "`sis-aga`")
public class Uploadmobile implements java.io.Serializable {

    private Integer id;
    private String path;
    private String extension;
    private String moisannee;

    public Uploadmobile() {
    }

    public Uploadmobile(String path, String extension, String moisannee) {
        this.path = path;
        this.extension = extension;
        this.moisannee = moisannee;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "PATH")
    public String getPath() {
        return this.path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    @Column(name = "EXTENSION")
    public String getExtension() {
        return this.extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    @Column(name = "MOISANNEE")
    public String getMoisannee() {
        return this.moisannee;
    }

    public void setMoisannee(String moisannee) {
        this.moisannee = moisannee;
    }

}
